services:
  blog-project-api:
    image: tientrandevops/blog-project-server:latest
    build:
      context: ./BlogProjectServer
      dockerfile: ./api/Dockerfile

  blog-project-client:
    image: tientrandevops/blog-project-client:latest
    build:
      context: ./BlogProjectClient
      dockerfile: Dockerfile
      args:
        GOOGLE_ID: ${GOOGLE_CLIENT_ID}
        API_ENDPOINT: ${API_ENDPOINT}
